version: '3.0'
services:
  api:
    image: quay.io/tribuvan/smartcow:api-v1
    container_name: api
    ports:
    - "8000:8000"
    extra_hosts:
    - host.docker.internal:host-gateway
  node:
    image: quay.io/tribuvan/smartcow:node-v1
    container_name: node
    ports:
    - "3000:3000"
    extra_hosts:
    - host.docker.internal:host-gateway
  nginx:
    image: quay.io/tribuvan/smartcow:nginx-v1
    container_name: nginx
    ports:
    - "8080:80"
    extra_hosts:
    - host.docker.internal:host-gateway